import { useEffect, useMemo, useState } from 'react'
import {
  getMyGroups,
  getGroupStudents,
  getCertificates,
  createCertificate,
  deleteCertificate,
} from '../../lib/api'
import type { Certificate } from '../../types'

type Student = {
  id: string
  name: string
  email?: string
}

type CourseOption = {
  id: string
  name: string
}

type StudentCourse = {
  studentId: string
  courseId: string
  courseName: string
}

export default function TeacherCertificates() {
  const [students, setStudents] = useState<Student[]>([])
  const [courses, setCourses] = useState<CourseOption[]>([])
  const [studentCourses, setStudentCourses] = useState<StudentCourse[]>([])
  const [certs, setCerts] = useState<Certificate[]>([])

  const [studentId, setStudentId] = useState('')
  const [courseId, setCourseId] = useState('')

  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const [showModal, setShowModal] = useState(false)

  const loadAll = async () => {
    try {
      setLoading(true)
      setError('')

      const groupsRes = await getMyGroups()
      const groups = Array.isArray(groupsRes?.data)
        ? groupsRes.data
        : []

      const studentMap = new Map<string, Student>()
      const courseMap = new Map<string, CourseOption>()
      const studentCourseMap = new Map<string, StudentCourse>()

      for (const group of groups) {
        const groupId = group.id
        const groupCourseId = String(
          group.course_id ?? group.courseId ?? ''
        )
        const groupCourseName =
          group.course_name ??
          group.courseName ??
          'Course'

        if (groupCourseId) {
          courseMap.set(groupCourseId, {
            id: groupCourseId,
            name: groupCourseName,
          })
        }

        try {
          const studentsRes = await getGroupStudents(groupId)
          const groupStudents = Array.isArray(studentsRes?.data)
            ? studentsRes.data
            : []

          groupStudents.forEach((student: any) => {
            const sid = String(student.id)

            studentMap.set(sid, {
              id: sid,
              name: student.name,
              email: student.email,
            })

            if (groupCourseId) {
              const key = `${sid}-${groupCourseId}`

              studentCourseMap.set(key, {
                studentId: sid,
                courseId: groupCourseId,
                courseName: groupCourseName,
              })
            }
          })
        } catch {
          // One group failing should not prevent other groups from loading.
        }
      }

      const certificatesRes = await getCertificates()

      const studentList = Array.from(studentMap.values()).sort(
        (a, b) => a.name.localeCompare(b.name)
      )

      const courseList = Array.from(courseMap.values()).sort(
        (a, b) => a.name.localeCompare(b.name)
      )

      setStudents(studentList)
      setCourses(courseList)
      setStudentCourses(Array.from(studentCourseMap.values()))
      setCerts(
        Array.isArray(certificatesRes?.data)
          ? certificatesRes.data
          : []
      )

      if (studentList.length > 0) {
        setStudentId((current) => current || studentList[0].id)
      }
    } catch (err: any) {
      setError(err?.message || 'Failed to load certificates')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    loadAll()
  }, [])

  const availableCourses = useMemo(() => {
    if (!studentId) return []

    const ids = new Set(
      studentCourses
        .filter((x) => x.studentId === studentId)
        .map((x) => x.courseId)
    )

    return courses.filter((course) => ids.has(course.id))
  }, [studentId, studentCourses, courses])

  useEffect(() => {
    if (!studentId) {
      setCourseId('')
      return
    }

    const available = studentCourses.filter(
      (x) => x.studentId === studentId
    )

    setCourseId(available[0]?.courseId || '')
  }, [studentId, studentCourses])

  const selectedStudent = students.find(
    (s) => s.id === studentId
  )

  const selectedCourse = availableCourses.find(
    (c) => c.id === courseId
  )

  const issueCertificate = async () => {
    if (!studentId || !courseId || !selectedCourse) return

    try {
      setSaving(true)
      setError('')

      await createCertificate({
        student_id: studentId,

        // The existing certificates table already has a "name"
        // field, so we use it as the course name.
        name: selectedCourse.name,

        // The certificate is generated by Lexicon.
        issuing_organization: 'Lexicon',

        issue_date: new Date()
          .toISOString()
          .split('T')[0],

        certificate_code: `LEX-${Date.now()}`,
      })

      setShowModal(false)

      const certificatesRes = await getCertificates()

      setCerts(
        Array.isArray(certificatesRes?.data)
          ? certificatesRes.data
          : []
      )
    } catch (err: any) {
      setError(
        err?.message || 'Failed to issue certificate'
      )
    } finally {
      setSaving(false)
    }
  }

  const removeCertificate = async (id: string) => {
    if (
      !window.confirm(
        'Are you sure you want to delete this certificate?'
      )
    ) {
      return
    }

    try {
      setError('')

      await deleteCertificate(id)

      setCerts((prev) =>
        prev.filter((certificate) => certificate.id !== id)
      )
    } catch (err: any) {
      setError(
        err?.message || 'Failed to delete certificate'
      )
    }
  }

  if (loading) {
    return (
      <div className="p-6">
        Loading certificates...
      </div>
    )
  }

  return (
    <div className="p-6 max-w-6xl mx-auto">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1
            className="text-2xl font-semibold"
            style={{ fontFamily: 'Outfit, sans-serif' }}
          >
            Certificates
          </h1>

          <p
            className="text-sm mt-1"
            style={{ color: 'var(--muted-foreground)' }}
          >
            Issue Lexicon course certificates to your students.
          </p>
        </div>

        <button
          onClick={() => setShowModal(true)}
          disabled={!students.length}
          className="text-sm font-semibold px-4 py-2 rounded-lg"
          style={{
            background: 'var(--primary)',
            color: 'white',
            border: 'none',
            cursor: students.length
              ? 'pointer'
              : 'not-allowed',
            opacity: students.length ? 1 : 0.5,
          }}
        >
          + Issue Certificate
        </button>
      </div>

      {error && (
        <div
          className="mb-5 p-3 rounded-lg text-sm"
          style={{
            background: '#FEE2E2',
            color: '#B91C1C',
          }}
        >
          {error}
        </div>
      )}

      {!students.length ? (
        <div
          className="rounded-xl p-10 text-center"
          style={{
            background: 'var(--card)',
            border: '1px solid var(--border)',
          }}
        >
          <p className="font-medium">
            No students assigned.
          </p>

          <p
            className="text-sm mt-1"
            style={{ color: 'var(--muted-foreground)' }}
          >
            You need students in one of your groups before
            issuing certificates.
          </p>
        </div>
      ) : certs.length === 0 ? (
        <div
          className="rounded-xl p-10 text-center"
          style={{
            background: 'var(--card)',
            border: '1px solid var(--border)',
          }}
        >
          <p className="font-medium">
            No certificates issued yet.
          </p>

          <p
            className="text-sm mt-1"
            style={{ color: 'var(--muted-foreground)' }}
          >
            Issue a course certificate using the button above.
          </p>
        </div>
      ) : (
        <div
          className="rounded-xl overflow-hidden"
          style={{
            background: 'var(--card)',
            border: '1px solid var(--border)',
          }}
        >
          <table className="w-full">
            <thead>
              <tr
                style={{
                  background: 'var(--muted)',
                  borderBottom:
                    '1px solid var(--border)',
                }}
              >
                {[
                  'Student',
                  'Course',
                  'Issue Date',
                  'Certificate ID',
                  'Actions',
                ].map((heading) => (
                  <th
                    key={heading}
                    className="px-4 py-3 text-left text-xs uppercase tracking-wider"
                    style={{
                      color:
                        'var(--muted-foreground)',
                    }}
                  >
                    {heading}
                  </th>
                ))}
              </tr>
            </thead>

            <tbody>
              {certs.map((certificate, index) => (
                <tr
                  key={certificate.id}
                  style={{
                    borderBottom:
                      index < certs.length - 1
                        ? '1px solid var(--border)'
                        : 'none',
                  }}
                >
                  <td className="px-4 py-4 text-sm font-medium">
                    {certificate.studentName || '—'}
                  </td>

                  <td className="px-4 py-4 text-sm">
                    {certificate.name}
                  </td>

                  <td className="px-4 py-4 text-sm">
                    {certificate.issueDate || '—'}
                  </td>

                  <td
                    className="px-4 py-4 text-xs mono"
                    style={{
                      color:
                        'var(--muted-foreground)',
                    }}
                  >
                    {certificate.certificateCode ||
                      '—'}
                  </td>

                  <td className="px-4 py-4">
                    <button
                      onClick={() =>
                        removeCertificate(
                          certificate.id
                        )
                      }
                      className="text-xs px-3 py-1.5 rounded-lg"
                      style={{
                        background: '#FEE2E2',
                        color: '#B91C1C',
                        border: 'none',
                        cursor: 'pointer',
                      }}
                    >
                      Delete
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {showModal && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4"
          style={{
            background: 'rgba(0,0,0,0.4)',
          }}
          onClick={() => setShowModal(false)}
        >
          <div
            className="rounded-xl p-6 w-full max-w-md"
            style={{
              background: 'var(--card)',
              border: '1px solid var(--border)',
              boxShadow:
                '0 20px 60px rgba(0,0,0,0.2)',
            }}
            onClick={(e) => e.stopPropagation()}
          >
            <h2
              className="text-lg font-semibold mb-2"
              style={{
                fontFamily: 'Outfit, sans-serif',
              }}
            >
              Issue Certificate
            </h2>

            <p
              className="text-sm mb-5"
              style={{
                color: 'var(--muted-foreground)',
              }}
            >
              Select the student and course. The
              certificate will use the Lexicon template
              automatically.
            </p>

            <div className="space-y-4">
              <div>
                <label
                  className="block text-xs font-semibold mb-1.5"
                  style={{
                    color:
                      'var(--muted-foreground)',
                  }}
                >
                  Student
                </label>

                <select
                  value={studentId}
                  onChange={(e) =>
                    setStudentId(e.target.value)
                  }
                  className="w-full px-3 py-2.5 rounded-lg text-sm"
                  style={{
                    border:
                      '1px solid var(--border)',
                    background: 'var(--muted)',
                    outline: 'none',
                  }}
                >
                  <option value="">
                    Select student...
                  </option>

                  {students.map((student) => (
                    <option
                      key={student.id}
                      value={student.id}
                    >
                      {student.name}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label
                  className="block text-xs font-semibold mb-1.5"
                  style={{
                    color:
                      'var(--muted-foreground)',
                  }}
                >
                  Course
                </label>

                <select
                  value={courseId}
                  onChange={(e) =>
                    setCourseId(e.target.value)
                  }
                  className="w-full px-3 py-2.5 rounded-lg text-sm"
                  style={{
                    border:
                      '1px solid var(--border)',
                    background: 'var(--muted)',
                    outline: 'none',
                  }}
                >
                  <option value="">
                    Select course...
                  </option>

                  {availableCourses.map((course) => (
                    <option
                      key={course.id}
                      value={course.id}
                    >
                      {course.name}
                    </option>
                  ))}
                </select>

                {!availableCourses.length &&
                  studentId && (
                    <p
                      className="text-xs mt-1"
                      style={{
                        color:
                          'var(--muted-foreground)',
                      }}
                    >
                      This student is not enrolled in
                      one of your courses.
                    </p>
                  )}
              </div>

              {selectedStudent &&
                selectedCourse && (
                  <div
                    className="rounded-lg p-4"
                    style={{
                      background: 'var(--muted)',
                      border:
                        '1px solid var(--border)',
                    }}
                  >
                    <p className="text-xs uppercase tracking-wider font-semibold">
                      Certificate Preview
                    </p>

                    <p className="text-sm font-semibold mt-2">
                      {selectedStudent.name}
                    </p>

                    <p
                      className="text-sm mt-1"
                      style={{
                        color:
                          'var(--muted-foreground)',
                      }}
                    >
                      {selectedCourse.name}
                    </p>

                    <p
                      className="text-xs mt-2"
                      style={{
                        color:
                          'var(--muted-foreground)',
                      }}
                    >
                      Issued by Lexicon
                    </p>
                  </div>
                )}
            </div>

            <div className="flex gap-3 mt-6">
              <button
                onClick={() =>
                  setShowModal(false)
                }
                className="flex-1 py-2.5 rounded-lg text-sm"
                style={{
                  border:
                    '1px solid var(--border)',
                  background: 'transparent',
                  cursor: 'pointer',
                }}
              >
                Cancel
              </button>

              <button
                onClick={issueCertificate}
                disabled={
                  saving ||
                  !studentId ||
                  !courseId ||
                  !selectedCourse
                }
                className="flex-1 py-2.5 rounded-lg text-sm font-semibold"
                style={{
                  background: 'var(--primary)',
                  color: 'white',
                  border: 'none',
                  cursor: 'pointer',
                  opacity:
                    saving ||
                    !studentId ||
                    !courseId ||
                    !selectedCourse
                      ? 0.5
                      : 1,
                }}
              >
                {saving
                  ? 'Issuing...'
                  : 'Issue Certificate'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}