import { useEffect, useState } from 'react'
import StatCard from '../../components/StatCard'
import { getAnalyticsOverview, getGroupAnalytics, getGroups, getUsers } from '../../lib/api'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts'

export default function AdminDashboard(){
 const [students,setStudents]=useState<any[]>([]),[teachers,setTeachers]=useState<any[]>([]),[groups,setGroups]=useState<any[]>([]),[performance,setPerformance]=useState<any[]>([]),[attendance,setAttendance]=useState(0),[loading,setLoading]=useState(true)
 useEffect(()=>{(async()=>{try{const [s,t,g,p,o]:any[]=await Promise.all([getUsers('student'),getUsers('teacher'),getGroups(),getGroupAnalytics(),getAnalyticsOverview()]);setStudents(s.data??[]);setTeachers(t.data??[]);setGroups(g.data??[]);setPerformance((p.data??[]).map((x:any)=>({group:x.name,attendance:Number(x.attendance??0),quizAvg:Number(x.quizAvg??0),assessmentAvg:Number(x.assessmentAvg??0)})));setAttendance(Number(o.data?.attendance?.rate??0))}finally{setLoading(false)}})()},[])
 if(loading)return <div className="p-6">Loading dashboard…</div>
 return <div className="p-6 max-w-6xl mx-auto"><div className="mb-6"><h1 className="text-2xl font-semibold">Overview</h1><p className="text-sm mt-0.5" style={{color:'var(--muted-foreground)'}}>Live organisation data from the database</p></div>
 <div className="grid gap-4 mb-6" style={{gridTemplateColumns:'repeat(4,1fr)'}}><StatCard label="Total Students" value={students.length} sub="Across all groups" icon={<span>🎓</span>} accent/><StatCard label="Total Teachers" value={teachers.length} sub="Active instructors" icon={<span>👤</span>}/><StatCard label="Active Groups" value={groups.length} sub="Current groups" icon={<span>🗂</span>}/><StatCard label="Avg Attendance" value={`${attendance}%`} sub="Current records" icon={<span>✓</span>}/></div>
 <div className="rounded-xl p-5 mb-6" style={{background:'var(--card)',border:'1px solid var(--border)'}}><h2 className="text-base font-semibold mb-4">Group Performance</h2><ResponsiveContainer width="100%" height={280}><BarChart data={performance}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="group"/><YAxis domain={[0,100]}/><Tooltip/><Legend/><Bar dataKey="attendance" name="Attendance %"/><Bar dataKey="quizAvg" name="Quiz Avg %"/><Bar dataKey="assessmentAvg" name="Assessment Avg %"/></BarChart></ResponsiveContainer></div>
 <div className="rounded-xl overflow-hidden" style={{background:'var(--card)',border:'1px solid var(--border)'}}><div className="px-5 py-4 border-b"><h2 className="text-base font-semibold">Active Groups</h2></div><table className="w-full"><thead><tr style={{borderBottom:'1px solid var(--border)'}}>{['Group','Course','Students'].map(h=><th key={h} className="px-5 py-3 text-left text-xs uppercase" style={{color:'var(--muted-foreground)'}}>{h}</th>)}</tr></thead><tbody>{groups.map((g:any,i:number)=><tr key={g.id} style={{borderBottom:i<groups.length-1?'1px solid var(--border)':'none'}}><td className="px-5 py-3.5 text-sm font-medium">{g.name}</td><td className="px-5 py-3.5 text-sm">{g.course_name??'—'}</td><td className="px-5 py-3.5 text-sm">{g.student_count??'—'}</td></tr>)}</tbody></table></div>
 </div>
}